#!/usr/bin/env groovy

pipeline {
    agent any
    
    environment{
        DOCKER_CREDS = credentials('github-Container-creds')
        IMAGE_TAGGED = "ghcr.io/ruanfreits/workout-platform-frontend:latest"
        PRIVATE_KEY_FILE = 'id_rsa_temp'
    }
    stages {
        stage('Login to Docker') {
            steps {
                // Use the DOCKER_CREDS environment variable, which automatically
                // provides DOCKER_CREDS_USR and DOCKER_CREDS_PSW
                sh "docker login -u \$DOCKER_CREDS_USR -p \$DOCKER_CREDS_PSW ghcr.io"
            }
        }
        stage('Build-Image') {
            steps {
                configFileProvider([configFile(fileId: 'c3b6e546-7eef-4758-bc4a-fceb4189249c',variable: 'APP_FRONTEND_ENV')]){
                script{
                sh 'cp $APP_FRONTEND_ENV .env'
                app = docker.build("gym-project-frontend/test")
                sh 'docker tag gym-project-frontend/test:latest ghcr.io/ruanfreits/workout-platform-frontend:latest'
                sh 'docker push ghcr.io/ruanfreits/workout-platform-frontend:latest'
                sh 'rm .env'
                }
            }
        }
    }
        stage('Deploy'){
                steps{
                    withCredentials([sshUserPrivateKey(credentialsId: 'jenkins-remote', keyFileVariable: 'SSH_KEY')]) {
                            sh '''
                                rm -f /tmp/jenkins_keys/id_rsa_temp || true &&

                                mkdir -p /tmp/jenkins_keys
                                install -m 600 $SSH_KEY /tmp/jenkins_keys/$PRIVATE_KEY_FILE
                                
                                ls -l /tmp/jenkins_keys

                                
                                ssh -i /tmp/jenkins_keys/$PRIVATE_KEY_FILE -o StrictHostKeyChecking=no  vboxuser@192.168.0.72 '
                                ls -l /home
                                docker pull ghcr.io/ruanfreits/workout-platform-frontend:latest &&
                                docker rm -f nginx_front || true &&
                                docker run -d  -p 80:80 --name nginx_front ghcr.io/ruanfreits/workout-platform-frontend:latest'
                            '''
                        }
            }
        }



    }
}